name: build
on: [push]
jobs:
  buildJob:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - run: chmod +x gradlew
      - run: dir
      - run: tar -xvzf art/module.tar.gz
      - name: Build Gradle
        run: ./gradlew app:assembleDebug