name: build
on: [push, pull_request]
jobs:
  buildJob:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - run: chmod +x gradlew
      - run: tar -xvzf art/module.tar.gz
      - run: echo tmdb_api_key=${{ secrets.TMDB_API_KEY }} >> local.properties
      - run: echo google_client_id_web=${{ secrets.GOOGLE_CLIENT_WEB_ID }} >> local.properties
      - run: echo ${{ secrets.GOOGLE_JSON }} >> app\google-services.json
      - name: Build Gradle
        run: ./gradlew app:assembleDebug --stacktrace
      - name: Upload APK
        uses: actions/upload-artifact@v2-preview
        with:
          name: app
          path: app/build/outputs/apk/debug/app-debug.apk

  notification:
    needs: [buildJob]
    runs-on: ubuntu-latest
    steps:
      - name: Set outputs
        id: vars
        run: echo "::set-output name=sha_short::$(echo ${{ github.sha }} | cut -c -7)"
      - name: Sending complete notifications
        env:
          DISCORD_WEBHOOK: ${{ secrets.WEBHOOK }}
        uses: Ilshidur/action-discord@master
        with:
          args: "${{ github.event.repository.full_name }} with commit ${{ steps.vars.outputs.sha_short }} had a successful build!"
