name: build
on: [push, pull_request]
jobs:
  buildJob:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - run: chmod +x gradlew
      - run: tar -xvzf art/module.tar.gz
      - run: echo tmdb_api_key=${{ secrets.TMDB_API_KEY }} >> local.properties
      - run: echo google_client_id_web=${{ secrets.GOOGLE_CLIENT_WEB_ID }} >> local.properties
      - name: Build Gradle
        run: ./gradlew app:assembleDebug --stacktrace
      - name: Upload APK
        uses: actions/upload-artifact@v2-preview
        with:
          name: app
          path: app/build/outputs/apk/debug/app-debug.apk
